production:
  adapter: postgresql
  encoding: unicode
  database: db/production
  username: postgres
  password: abbuchi
  pool: 5
  timeout: 5000
  
development:
  adapter: postgresql
  encoding: unicode
  database: db/development
  username: postgres
  password: abbuchi
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: db/test
  username: postgres
  password: abbuchi
  pool: 5
